---
name: Increment Git Tag
description: Increments git tag based on the provided version type
inputs:
  version-type:
    description: Provide Version Type [major, minor, patch]
    required: true
    default: patch
outputs:
  new-version:
    description: Incremented version based on the input
runs:
  using: node12
  main: action/index.js